'use strict';
// Patch feature gates — computes globalThis.__clawgodPatches before the
// patched cli loads. Config: user-edited ~/.clawgod/patches.json
// ({"<feature>": false}, absent key = on). Per-feature env overrides for a
// single launch: CLAWGOD_FEATURE_<NAME>=false (feature id upper-cased,
// dashes → underscores, e.g. CLAWGOD_FEATURE_GEO_NEUTRALIZE=false; "true"
// restores a feature disabled in patches.json). CLAWGOD_FEATURES_META
// below is machine-generated by build.js from the FEATURES registry in
// patch.mjs (single source of truth) — do not hand-edit. Each gated patch in
// cli.original.cjs checks its own entry:
//   globalThis.__clawgodPatches?.["<patchId>"] !== false
// Absent/failed config → gate table absent → all gates default ON, which is
// exactly the pre-toggle behavior.
// {{CLAWGOD:FEATURES_META}}

// Features realized by the wrapper itself rather than by a baked patch id:
// they read the same patches.json / CLAWGOD_FEATURE_* inputs, but their
// consumer is cli.cjs (or a module it loads) instead of a runtime gate in
// cli.original.cjs. Their gate lands in the same __clawgodPatches table.
var CLAWGOD_RUNTIME_FEATURES = ['bun-ant-shim'];

var clawgodDir = require('path').join(require('os').homedir(), '.clawgod');

var _cfg = {};
try { _cfg = JSON.parse(require('fs').readFileSync(require('path').join(clawgodDir, 'patches.json'), 'utf8')); } catch {}
for (var _name in process.env) {
  if (_name.indexOf('CLAWGOD_FEATURE_') !== 0) continue;
  var _val = process.env[_name];
  if (_val !== 'true' && _val !== 'false') continue;
  _cfg[_name.slice('CLAWGOD_FEATURE_'.length).toLowerCase().replace(/_/g, '-')] = _val === 'true';
}

// META keys are patch ids; a feature id is "known" when some patch lists it
// or when the wrapper owns it (CLAWGOD_RUNTIME_FEATURES).
// Unknown keys are residue (renamed/removed features).
for (var _k in _cfg) {
  var _known = CLAWGOD_RUNTIME_FEATURES.indexOf(_k) >= 0;
  for (var _f in CLAWGOD_FEATURES_META) {
    if (CLAWGOD_FEATURES_META[_f].indexOf(_k) >= 0) { _known = true; break; }
  }
  if (!_known) process.stderr.write('[clawgod] warning: unknown feature "' + _k + '" in patches.json\n');
}

var _gate = {};
for (var _pid in CLAWGOD_FEATURES_META) {
  var _feats = CLAWGOD_FEATURES_META[_pid];
  var _on = false;
  for (var _j = 0; _j < _feats.length; _j++) {
    if (_cfg[_feats[_j]] !== false) { _on = true; break; }
  }
  _gate[_pid] = _on;
}
for (var _rfi = 0; _rfi < CLAWGOD_RUNTIME_FEATURES.length; _rfi++) {
  _gate[CLAWGOD_RUNTIME_FEATURES[_rfi]] = _cfg[CLAWGOD_RUNTIME_FEATURES[_rfi]] !== false;
}
globalThis.__clawgodPatches = _gate;
